[font]
size = 16

[font.bold]
family = "ZedMono Nerd Font Propo"
style = "Bold"

[font.bold_italic]
family = "ZedMono Nerd Font Propo"
style = "Bold Italic"

[font.italic]
family = "ZedMono Nerd Font Propo"
style = "Italic"

[font.normal]
family = "ZedMono Nerd Font"
style = "Regular"

[window]
opacity = 0.9
padding = { x = 4, y = 4 }

[general]
import = [ 
"~/.config/alacritty/themes/colors.toml" 
]
