"$schema" = 'https://starship.rs/config-schema.json'

format = '''
$directory$git_branch$rust$python
$character'''

palette = 'colors'

[palettes.colors]
color1 = '#b7c7e7'
color2 = '#21314a'
color3 = '#c5c6ce'
color4 = '#1f1f21'
color5 = '#21314a'
color6 = '#131315'
color7 = '#131315'
color8 = '#b7c7e7'
color9 = '#dfbcdb'

# Prompt symbols 
[character]
success_symbol = "[ ](color9 bold)"
error_symbol = "[ ](@{error})"
vicmd_symbol = "[](#f9e2af)"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
