"$schema" = 'https://starship.rs/config-schema.json'

format = '''
$directory$git_branch$rust$python
$character'''

palette = 'colors'

[palettes.colors]
color1 = '#dac3a2'
color2 = '#3c2e17'
color3 = '#cfc5b9'
color4 = '#211f1d'
color5 = '#3c2e17'
color6 = '#151311'
color7 = '#151311'
color8 = '#ffedd5'
color9 = '#ecf2d2'

# Prompt symbols 
[character]
success_symbol = "[ ](color9 bold)"
error_symbol = "[ ](@{error})"
vicmd_symbol = "[](#f9e2af)"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
