[colors.primary]
background = '#151311'
foreground = '#e7e1dd'
 
[colors.cursor]
text = '#e7e1dd'
cursor = '#cfc5b9' 
 
[colors.vi_mode_cursor]
text = '#151311'
cursor = '#ffedd5' 
 
[colors.search.matches]
foreground = '#4c463d' 
background = '#ecf2d2' 
 
[colors.search.focused_match]
foreground = '#4c463d' 
background = '#ffedd5' 
 
[colors.footer_bar]
foreground = '#4c463d' 
background = '#e7e1dd' 
 
[colors.hints.start]
foreground = '#4c463d' 
background = '#d1c5b5' 
 
[colors.hints.end]
foreground = '#4c463d' 
background = '#d1c5b5' 
 
[colors.selection]
text = '#151311'
background = '#ffedd5'
 
 
[colors.normal]
black = '#181818' 
red = '#ffb4ab' 
green = '#ffedd5' 
yellow = '#6d5c41' 
blue = '#ffedd5' 
magenta = '#ecf2d2' 
cyan = '#d1c5b5' 
white = '#FFFFFF' 
 
 
[colors.bright]
black = '#585B70' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#A6ADC8' 
 
 
[colors.dim]
black = '#45475A' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#BAC2DE' 
