[colors.primary]
background = '#131315'
foreground = '#e4e2e4'
 
[colors.cursor]
text = '#e4e2e4'
cursor = '#c5c6ce' 
 
[colors.vi_mode_cursor]
text = '#131315'
cursor = '#b7c7e7' 
 
[colors.search.matches]
foreground = '#44474d' 
background = '#dfbcdb' 
 
[colors.search.focused_match]
foreground = '#44474d' 
background = '#b7c7e7' 
 
[colors.footer_bar]
foreground = '#44474d' 
background = '#e4e2e4' 
 
[colors.hints.start]
foreground = '#44474d' 
background = '#c1c6d4' 
 
[colors.hints.end]
foreground = '#44474d' 
background = '#c1c6d4' 
 
[colors.selection]
text = '#131315'
background = '#b7c7e7'
 
 
[colors.normal]
black = '#181818' 
red = '#ffb4ab' 
green = '#b7c7e7' 
yellow = '#4f5f7b' 
blue = '#b7c7e7' 
magenta = '#dfbcdb' 
cyan = '#c1c6d4' 
white = '#FFFFFF' 
 
 
[colors.bright]
black = '#585B70' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#A6ADC8' 
 
 
[colors.dim]
black = '#45475A' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#BAC2DE' 
